trab1: Menu.c Algoritmo_1.c Algoritmo_2.c Algoritmo_3.c Pilha_c_func.c Pilha_func.c Suporte_func.c Valida_exp_func.c Valida_func.c
	gcc -o trab1 Menu.c Algoritmo_1.c Algoritmo_2.c Algoritmo_3.c Pilha_c_func.c Pilha_func.c Suporte_func.c Valida_exp_func.c Valida_func.c -I.
